export const SET_DISPLAY_VALUE = 'SET_DISPLAY_VALUE';
export const SET_FIRST_VALUE = 'SET_FIRST_VALUE';
export const SET_SECOND_VALUE = 'SET_SECOND_VALUE';
export const SET_MATH_SYMBOL = 'SET_MATH_SYMBOL';